import { StyleSheet, Dimensions } from "react-native";
import { COLORS, SPACING, RADIUS } from "../constants/theme";

const { width } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.bg },
  loadingContainer: { flex: 1, backgroundColor: COLORS.bg, alignItems: 'center', justifyContent: 'center' },

  bannerWrap: { height: 300, position: 'relative' },
  banner: { ...StyleSheet.absoluteFillObject },
  bannerOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(8,8,16,0.5)',
  },
  backBtn: {
    position: 'absolute', left: SPACING.md,
    width: 38, height: 38, borderRadius: 19,
    backgroundColor: 'rgba(8,8,16,0.7)',
    alignItems: 'center', justifyContent: 'center',
    borderWidth: 1, borderColor: COLORS.border,
  },
  posterRow: {
    position: 'absolute', bottom: -SPACING.xl,
    left: SPACING.md, right: SPACING.md,
    flexDirection: 'row', gap: SPACING.md,
  },
  poster: {
    width: 110, height: 160,
    borderRadius: RADIUS.md,
    borderWidth: 2, borderColor: COLORS.border,
  },
  posterInfo: { flex: 1, paddingTop: SPACING.lg, justifyContent: 'flex-end', paddingBottom: SPACING.sm },
  title: { fontSize: 18, color: COLORS.text, fontWeight: '900', letterSpacing: -0.3, lineHeight: 22 },
  titleJp: { fontSize: 12, color: COLORS.textSub, marginTop: 3, letterSpacing: 0.5 },
  metaRow: { flexDirection: 'row', gap: 4, marginTop: SPACING.xs, flexWrap: 'wrap' },
  metaBadge: {
    paddingHorizontal: 7, paddingVertical: 2,
    backgroundColor: 'rgba(191,95,255,0.12)',
    borderRadius: RADIUS.sm, borderWidth: 1, borderColor: COLORS.border,
  },
  metaBadgeText: { fontSize: 10, color: COLORS.textSub, fontWeight: '600' },
  ratingRow: { flexDirection: 'row', alignItems: 'center', gap: 2, marginTop: SPACING.xs },
  ratingNum: { fontSize: 12, color: COLORS.neonGold, fontWeight: '700', marginLeft: 4 },

  actionRow: {
    flexDirection: 'row', gap: SPACING.sm,
    marginTop: SPACING.xxl + SPACING.sm,
    marginHorizontal: SPACING.md,
  },
  playBigBtn: {
    flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
    gap: SPACING.xs, backgroundColor: COLORS.neon,
    paddingVertical: 13, borderRadius: RADIUS.md,
  },
  playBigText: { color: COLORS.bg, fontWeight: '800', fontSize: 13, letterSpacing: 1 },
  playBigSub: { color: COLORS.bg, fontWeight: '500', fontSize: 10, opacity: 0.75, marginTop: 1 },
  iconActionBtn: {
    width: 48, height: 48,
    backgroundColor: COLORS.bgCard,
    borderRadius: RADIUS.md,
    alignItems: 'center', justifyContent: 'center',
    borderWidth: 1, borderColor: COLORS.border,
  },
  iconActionBtnActive: { borderColor: COLORS.neon, backgroundColor: 'rgba(191,95,255,0.1)' },
  iconActionBtnPink: { borderColor: COLORS.neonPink, backgroundColor: 'rgba(255,45,120,0.1)' },

  statsStrip: {
    flexDirection: 'row',
    marginHorizontal: SPACING.md,
    marginTop: SPACING.md,
    backgroundColor: COLORS.bgCard,
    borderRadius: RADIUS.md,
    borderWidth: 1, borderColor: COLORS.border,
    paddingVertical: SPACING.md,
  },
  statItem: { flex: 1, alignItems: 'center', gap: 3 },
  statDivider: { width: 1, backgroundColor: COLORS.border },
  statValue: { fontSize: 14, color: COLORS.text, fontWeight: '700' },
  statLabel: { fontSize: 10, color: COLORS.textMuted, letterSpacing: 0.5 },

  genreRow: { paddingHorizontal: SPACING.md, gap: SPACING.xs, marginTop: SPACING.md },
  genreTag: {
    paddingVertical: 5, paddingHorizontal: SPACING.sm,
    borderRadius: RADIUS.xl,
    backgroundColor: 'rgba(191,95,255,0.1)',
    borderWidth: 1, borderColor: 'rgba(191,95,255,0.3)',
  },
  genreTagText: { fontSize: 11, color: COLORS.neon, fontWeight: '600' },

  tabBar: {
    flexDirection: 'row',
    marginHorizontal: SPACING.md, marginTop: SPACING.lg,
    borderBottomWidth: 1, borderColor: COLORS.border,
  },
  tab: { flex: 1, paddingVertical: SPACING.sm, alignItems: 'center' },
  tabActive: { borderBottomWidth: 2, borderColor: COLORS.neon },
  tabText: { fontSize: 11, color: COLORS.textMuted, fontWeight: '700', letterSpacing: 1 },
  tabTextActive: { color: COLORS.neon },
  tabContent: { padding: SPACING.md },

  epRow: {
    flexDirection: 'row', alignItems: 'center', gap: SPACING.sm,
    paddingVertical: SPACING.sm,
    borderBottomWidth: 1, borderColor: COLORS.border,
  },
  downloadedBadge: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  epDownloadBtn: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  epNumWrap: {
    width: 36, height: 36,
    backgroundColor: COLORS.bgCard,
    borderRadius: RADIUS.sm,
    alignItems: 'center', justifyContent: 'center',
    borderWidth: 1, borderColor: COLORS.border,
  },
  epNum: { fontSize: 13, color: COLORS.neon, fontWeight: '700' },
  epInfo: { flex: 1 },
  epTitle: { fontSize: 14, color: COLORS.text, fontWeight: '600' },
  epMeta: { fontSize: 11, color: COLORS.textMuted, marginTop: 2 },

  seeAllEps: {
    marginTop: SPACING.md, alignItems: 'center',
    paddingVertical: SPACING.sm,
    borderWidth: 1, borderColor: COLORS.border,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.bgCard,
  },
  seeAllEpsText: { fontSize: 12, color: COLORS.neon, fontWeight: '700', letterSpacing: 1 },

  writeReviewBtn: {
    flexDirection: 'row', alignItems: 'center', gap: SPACING.xs,
    borderWidth: 1, borderColor: COLORS.neon,
    borderRadius: RADIUS.md, paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.md, marginBottom: SPACING.md,
    backgroundColor: 'rgba(191,95,255,0.08)',
    alignSelf: 'flex-start',
  },
  writeReviewText: { fontSize: 12, color: COLORS.neon, fontWeight: '700', letterSpacing: 1 },

  reviewSummary: {
    backgroundColor: COLORS.bgCard,
    padding: SPACING.md,
    borderRadius: RADIUS.md,
    marginBottom: SPACING.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.md,
    borderWidth: 1, borderColor: COLORS.border,
  },
  ratingBox: { alignItems: 'center', gap: 2 },
  ratingAvg: { fontSize: 24, color: COLORS.neonGold, fontWeight: '900' },
  starsRow: { flexDirection: 'row', gap: 1 },
  reviewCountLabel: { fontSize: 10, color: COLORS.textMuted, fontWeight: '600' },
  seeAllReviewsBtn: {
    flex: 1, height: 44,
    backgroundColor: 'rgba(191,95,255,0.08)',
    borderRadius: RADIUS.sm,
    alignItems: 'center', justifyContent: 'center',
    borderWidth: 1, borderColor: COLORS.neon,
  },
  seeAllReviewsText: { fontSize: 11, color: COLORS.neon, fontWeight: '800', letterSpacing: 1 },

  reviewCard: {
    backgroundColor: COLORS.bgCard,
    borderRadius: RADIUS.md,
    padding: SPACING.md,
    marginBottom: SPACING.sm,
    borderWidth: 1, borderColor: COLORS.border,
  },
  reviewHeader: { flexDirection: 'row', alignItems: 'center', gap: SPACING.sm, marginBottom: SPACING.xs },
  reviewAvatar: {
    width: 32, height: 32, borderRadius: 16,
    backgroundColor: 'rgba(191,95,255,0.2)',
    alignItems: 'center', justifyContent: 'center',
    borderWidth: 1, borderColor: COLORS.neon,
  },
  reviewAvatarText: { fontSize: 14, color: COLORS.neon, fontWeight: '700' },
  reviewUsername: { fontSize: 13, color: COLORS.text, fontWeight: '600' },
  reviewStars: { flexDirection: 'row', gap: 1, marginTop: 2 },
  spoilerBadge: {
    marginLeft: 'auto',
    backgroundColor: 'rgba(255,45,120,0.15)',
    borderRadius: RADIUS.sm, paddingHorizontal: 6, paddingVertical: 2,
    borderWidth: 1, borderColor: COLORS.neonPink,
  },
  spoilerText: { fontSize: 9, color: COLORS.neonPink, fontWeight: '700', letterSpacing: 1 },
  reviewText: { fontSize: 13, color: COLORS.textSub, lineHeight: 20 },

  infoBlock: { marginBottom: SPACING.lg },
  infoLabel: { fontSize: 11, color: COLORS.neon, fontWeight: '800', letterSpacing: 2, marginBottom: SPACING.xs },
  infoText: { fontSize: 14, color: COLORS.textSub, lineHeight: 22 },
  infoGrid: {
    backgroundColor: COLORS.bgCard, borderRadius: RADIUS.md,
    borderWidth: 1, borderColor: COLORS.border,
    overflow: 'hidden', marginBottom: SPACING.lg,
  },
  infoRow: {
    flexDirection: 'row', justifyContent: 'space-between',
    paddingHorizontal: SPACING.md, paddingVertical: SPACING.sm,
    borderBottomWidth: 1, borderColor: COLORS.border,
  },
  infoRowLabel: { fontSize: 13, color: COLORS.textMuted, fontWeight: '500' },
  infoRowValue: { fontSize: 13, color: COLORS.text, fontWeight: '600' },

  emptyState: { alignItems: 'center', padding: SPACING.xl },
  emptyText: { fontSize: 13, color: COLORS.textMuted },

  // Trailer styles
  trailerOverlayBtn: {
    position: 'absolute',
    right: SPACING.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.xs,
    backgroundColor: COLORS.bgGlass,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: RADIUS.sm,
    paddingHorizontal: SPACING.sm,
    paddingVertical: 6,
    height: 38,
    justifyContent: 'center',
  },
  trailerOverlayText: {
    color: COLORS.text,
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1,
  },
  trailerModalContainer: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(8, 8, 16, 0.85)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 9999,
  },
  trailerVideoCard: {
    backgroundColor: COLORS.bgCard,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.border,
    overflow: 'hidden',
    shadowColor: COLORS.neonCyan,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.4,
    shadowRadius: 16,
    elevation: 10,
  },
  trailerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    backgroundColor: COLORS.bgCard,
    borderBottomWidth: 1,
    borderColor: COLORS.border,
  },
  trailerHeaderTitle: {
    fontSize: 11,
    color: COLORS.neonCyan,
    fontWeight: '800',
    letterSpacing: 1.5,
  },
  closeTrailerBtn: {
    padding: SPACING.xs,
  },
  trailerPlayer: {
    backgroundColor: '#000',
    width: '100%',
  },

  // Shelves styles
  shelfContainer: {
    marginTop: SPACING.lg,
    paddingHorizontal: SPACING.md,
  },
  shelfTitle: {
    fontSize: 11,
    color: COLORS.neon,
    fontWeight: '800',
    letterSpacing: 2,
    marginBottom: SPACING.sm,
  },
  shelfScroll: {
    gap: SPACING.sm,
    paddingBottom: SPACING.xs,
  },

  // Relation Card
  relationCard: {
    width: 90,
    position: 'relative',
    gap: SPACING.xs,
  },
  relationPoster: {
    width: 90,
    height: 130,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  relationBadge: {
    position: 'absolute',
    top: 6,
    left: 6,
    backgroundColor: 'rgba(8, 8, 16, 0.85)',
    paddingHorizontal: 5,
    paddingVertical: 2,
    borderRadius: RADIUS.sm,
    borderWidth: 0.5,
    borderColor: COLORS.border,
  },
  relationBadgeText: {
    fontSize: 8,
    color: COLORS.neonCyan,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  relationText: {
    fontSize: 11,
    color: COLORS.textSub,
    fontWeight: '600',
    textAlign: 'center',
  },

  // Character Card
  charCard: {
    width: 80,
    alignItems: 'center',
    gap: 2,
  },
  charAvatarWrap: {
    width: 64,
    height: 64,
    borderRadius: 32,
    borderWidth: 2,
    borderColor: COLORS.border,
    overflow: 'hidden',
    marginBottom: 4,
  },
  charAvatar: {
    width: '100%',
    height: '100%',
  },
  charName: {
    fontSize: 11,
    color: COLORS.text,
    fontWeight: '700',
    textAlign: 'center',
  },
  charRole: {
    fontSize: 9,
    color: COLORS.textMuted,
    fontWeight: '500',
    textTransform: 'uppercase',
  },
  vaName: {
    fontSize: 9,
    color: COLORS.neonCyan,
    textAlign: 'center',
    opacity: 0.8,
  },

  // Character Modal styles
  charModalContainer: {
    flex: 1,
    backgroundColor: COLORS.bg,
  },
  charModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: SPACING.md,
    paddingTop: 50,
    paddingBottom: SPACING.sm,
    borderBottomWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.bgCard,
  },
  charModalBackBtn: {
    padding: SPACING.xs,
  },
  charModalTitle: {
    fontSize: 20,
    color: COLORS.neonCyan,
    fontWeight: '800',
    flex: 1,
    marginLeft: SPACING.md,
  },
  charRoleBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: RADIUS.sm,
  },
  charRoleBadgeMain: {
    backgroundColor: COLORS.neonGold,
  },
  charRoleBadgeSub: {
    backgroundColor: COLORS.bgCard,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  charRoleBadgeText: {
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  charModalContent: {
    padding: SPACING.md,
    alignItems: 'center',
    gap: SPACING.lg,
    paddingBottom: 40,
  },
  charModalImageWrap: {
    width: width * 0.7,
    height: width * 0.7,
    borderRadius: RADIUS.lg,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: COLORS.border,
    marginTop: SPACING.sm,
  },
  charModalImage: {
    width: '100%',
    height: '100%',
  },
  charModalSection: {
    width: '100%',
    gap: SPACING.sm,
  },
  charModalSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.xs,
  },
  charModalSectionTitle: {
    fontSize: 14,
    color: COLORS.text,
    fontWeight: '800',
    letterSpacing: 1,
  },
  charInfoBox: {
    backgroundColor: COLORS.bgCard,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: RADIUS.md,
    padding: SPACING.md,
    gap: SPACING.sm,
  },
  charInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  charInfoRowLabel: {
    fontSize: 13,
    color: COLORS.textSub,
    fontWeight: '700',
    marginRight: 6,
  },
  charJpBadge: {
    paddingHorizontal: 5,
    paddingVertical: 1,
    borderWidth: 1,
    borderColor: COLORS.success,
    borderRadius: 4,
    marginRight: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  charJpBadgeText: {
    fontSize: 9,
    color: COLORS.success,
    fontWeight: '800',
  },
  charAbcBadge: {
    paddingHorizontal: 5,
    paddingVertical: 1,
    borderWidth: 1,
    borderColor: COLORS.neonCyan,
    borderRadius: 4,
    marginRight: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  charAbcBadgeText: {
    fontSize: 9,
    color: COLORS.neonCyan,
    fontWeight: '800',
  },
  charInfoRowValue: {
    fontSize: 13,
    color: COLORS.text,
    fontWeight: '600',
  },
  charDescBox: {
    backgroundColor: COLORS.bgCard,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: RADIUS.md,
    padding: SPACING.md,
  },
  charDescText: {
    fontSize: 13,
    color: COLORS.textSub,
    lineHeight: 20,
  },
  charModalFooter: {
    padding: SPACING.md,
    borderTopWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.bgCard,
  },
  charModalCloseBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: COLORS.neonCyan,
    paddingVertical: 12,
    borderRadius: RADIUS.lg,
  },
  charModalCloseBtnText: {
    fontSize: 14,
    color: COLORS.bg,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
});
