import { StyleSheet } from "react-native";
import { COLORS } from "../constants/theme";

export const styles = StyleSheet.create({
  // ── Embedded player custom controls ──────────────────────────────────────
  embedControlsBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    paddingBottom: 24,
    paddingHorizontal: 20,
    gap: 8,
  },
  embedCenterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 32,
    marginBottom: 12,
  },
  embedCtrlBtn: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderRadius: 32,
    width: 52,
    height: 52,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.15)',
  },
  embedPlayBtn: {
    width: 64,
    height: 64,
    backgroundColor: 'rgba(0,245,180,0.12)',
    borderColor: 'rgba(0,245,180,0.4)',
    borderRadius: 32,
  },
  embedSeekLabel: {
    color: '#fff',
    fontSize: 9,
    fontWeight: '800',
    marginTop: 2,
    opacity: 0.8,
  },
  embedScrubRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  embedTimeLabel: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '700',
    opacity: 0.85,
    minWidth: 40,
    textAlign: 'center',
  },
  embedTrack: {
    flex: 1,
    height: 20,
    justifyContent: 'center',
  },
  embedTrackBg: {
    height: 5,
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: 3,
    overflow: 'hidden',
  },
  embedTrackFill: {
    height: '100%',
    backgroundColor: '#00F5FF',
    borderRadius: 3,
  },
  embedChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
    borderRadius: 6,
    paddingHorizontal: 7,
    paddingVertical: 4,
  },
  embedChipText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.4,
  },
  embedPicker: {
    position: 'absolute',
    bottom: 62,
    right: 20,
    backgroundColor: 'rgba(14,14,18,0.96)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    borderRadius: 12,
    paddingVertical: 6,
    minWidth: 130,
    shadowColor: '#000',
    shadowOpacity: 0.6,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 12,
  },
  embedPickerTitle: {
    color: 'rgba(255,255,255,0.45)',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.8,
    paddingHorizontal: 14,
    paddingBottom: 6,
    paddingTop: 4,
    textTransform: 'uppercase',
  },
  embedPickerItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.06)',
  },
  embedPickerItemActive: {
    backgroundColor: 'rgba(0,245,255,0.06)',
  },
  embedPickerItemText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '600',
    flex: 1,
  },

  // ── Main container ──────────────────────────────────────────────────────
  container: {
    flex: 1,
    backgroundColor: "#000",
    // Ensure the player fills the full display including areas behind the notch.
    // On Android this overrides WindowInsets that would otherwise leave blank bars
    // on the sides in landscape mode.
    ...StyleSheet.absoluteFillObject,
  },
  fullCenter: {
    flex: 1,
    backgroundColor: "#000",
    justifyContent: "center",
    alignItems: "center",
    gap: 12,
  },
  loadingText: {
    color: COLORS.textSub,
    fontSize: 13,
    fontWeight: "600",
    marginTop: 8,
  },
  errorTitle: {
    color: COLORS.text,
    fontSize: 20,
    fontWeight: "900",
    marginTop: 12,
  },
  errorSubtitle: {
    color: COLORS.textMuted,
    fontSize: 13,
    textAlign: "center",
    lineHeight: 20,
    paddingHorizontal: 32,
  },

  errorBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 28,
    paddingVertical: 12,
    backgroundColor: COLORS.neon,
    borderRadius: 24,
  },
  errorBtnSecondary: {
    backgroundColor: "transparent",
    borderWidth: 1.5,
    borderColor: COLORS.neon,
  },
  errorBtnRow: {
    flexDirection: "row",
    gap: 12,
    marginTop: 28,
    alignItems: "center",
    justifyContent: "center",
  },
  errorBtnText: { color: "#000", fontWeight: "800", fontSize: 13 },

  // Loading overlay sits over WebView while player boots
  playerLoadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.55)",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
  },

  // ── Error overlay — fully opaque so the white WebView page is hidden ────
  errorOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "#0E0E11",
    justifyContent: "center",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 32,
  },

  // ── HUD compact server chip ──────────────────────────────────────────────
  serverChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 100,
    borderWidth: 1,
    borderColor: "rgba(0,229,255,0.3)",
    backgroundColor: "rgba(0,0,0,0.45)",
  },
  /** Locked variant — pink border when free user has additional servers */
  serverChipLocked: {
    borderColor: "rgba(255,56,100,0.4)",
    backgroundColor: "rgba(255,56,100,0.08)",
  },
  serverChipText: {
    fontSize: 10,
    fontWeight: "800",
    color: COLORS.neonCyan,
    letterSpacing: 0.5,
  },
  serverChipLockLabel: {
    fontSize: 8,
    fontWeight: "900",
    color: COLORS.neonPink,
    letterSpacing: 1,
    backgroundColor: "rgba(255,56,100,0.2)",
    paddingHorizontal: 5,
    paddingVertical: 2,
    borderRadius: 4,
    overflow: "hidden",
  },

  // ── Error overlay "Switch Server" button ─────────────────────────────────
  errorSwitchBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(0,229,255,0.25)",
    backgroundColor: "rgba(0,229,255,0.07)",
    marginTop: 4,
  },
  errorSwitchBtnText: {
    fontSize: 13,
    fontWeight: "700",
    color: COLORS.neonCyan,
  },

  // HUD layer — floats over WebView, box-none so touches pass through to WebView
  hudLayer: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "space-between",
  },
  topGradient: { position: "absolute", top: 0, left: 0, right: 0, height: 120 },
  bottomGradient: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: 52,   // clears the ~44px player control bar
  },

  topHud: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    height: 64,          // explicit — limits touch intercept to button row only
    paddingHorizontal: 24,
    paddingTop: 20,
  },
  topHudLeft: { flex: 1, flexDirection: "row", alignItems: "center", gap: 14, marginRight: 16 },
  topHudRight: { flexDirection: "row", alignItems: "center", gap: 12 },
  animeTitle: {
    color: COLORS.neonCyan,
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 2,
  },
  episodeInfo: {
    color: COLORS.text,
    fontSize: 16,
    fontWeight: "900",
    marginTop: 2,
  },

  iconBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.12)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },

  // Mini progress chip in top-right
  progressChip: {
    height: 28,
    minWidth: 110,
    borderRadius: 14,
    backgroundColor: "rgba(0,0,0,0.45)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
  },
  progressChipFill: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    backgroundColor: COLORS.neon,
    opacity: 0.25,
  },
  progressChipText: {
    fontSize: 10,
    fontWeight: "800",
    color: COLORS.text,
    zIndex: 1,
  },

  selectorBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "rgba(255,255,255,0.1)",
    paddingHorizontal: 14,
    height: 40,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  selectorBtnText: {
    color: COLORS.text,
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 1,
  },

  resumeToast: { position: "absolute", top: 100, alignSelf: "center" },
  resumeToastBlur: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: "rgba(0,0,0,0.5)",
    overflow: "hidden",
  },
  resumeToastText: { color: COLORS.text, fontSize: 12, fontWeight: "700" },

  skipToast: { position: "absolute", top: 140, alignSelf: "center" },
  skipToastBlur: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: "rgba(0,0,0,0.5)",
    overflow: "hidden",
  },
  skipToastText: { color: COLORS.text, fontSize: 12, fontWeight: "700" },

  nextUpCard: {
    position: "absolute",
    bottom: 24,
    right: 20,
    width: 280,
    borderRadius: 14,
    overflow: "hidden",
  },
  nextUpBlur: {
    flexDirection: "row",
    alignItems: "center",
    padding: 10,
    gap: 12,
  },
  nextUpClickableArea: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  nextUpThumb: {
    width: 48,
    height: 48,
    borderRadius: 8,
    backgroundColor: COLORS.bgElevated,
  },
  nextUpLabel: {
    fontSize: 8,
    fontWeight: "900",
    color: COLORS.neonCyan,
    letterSpacing: 1,
  },
  nextUpTitle: {
    fontSize: 11,
    fontWeight: "700",
    color: COLORS.text,
    marginTop: 2,
  },
  // Play now button (gold circle)
  nextUpPlayBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: COLORS.neonGold,
    alignItems: "center",
    justifyContent: "center",
  },
  // Cancel countdown (X) button
  nextUpCancelBtn: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,0.12)",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: -4,
  },

  modalBg: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.6)",
  },
  selectorSheet: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    padding: 32,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    borderWidth: 1,
    borderColor: "rgba(189,157,255,0.2)",
  },
  selectorHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 24,
    alignItems: "center",
  },
  selectorTitle: {
    fontSize: 24,
    fontWeight: "900",
    color: COLORS.neon,
    letterSpacing: -1,
    fontStyle: "italic",
  },
  selectorList: { gap: 16, paddingBottom: 20 },
  selectorItem: { width: 180, gap: 12 },
  activeItem: { opacity: 1 },
  selectorThumb: {
    width: "100%",
    height: 100,
    borderRadius: 12,
    backgroundColor: COLORS.bgElevated,
  },
  selectorInfo: { gap: 2 },
  selectorEpNum: {
    fontSize: 8,
    fontWeight: "800",
    color: COLORS.textSub,
    letterSpacing: 1,
  },
  selectorEpTitle: { fontSize: 12, fontWeight: "700", color: COLORS.text },
  selectorEpDur: { fontSize: 10, fontWeight: "500", color: COLORS.textSub },
  nowPlayingBadge: {
    position: "absolute",
    top: 8,
    left: 8,
    backgroundColor: COLORS.neon,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  nowPlayingText: { fontSize: 7, fontWeight: "900", color: "#000" },
});
